cliente:mainmenu.o quarto.o sala.o temperatura.o conect.o client.o
	gcc mainmenu.o quarto.o sala.o temperatura.o conect.o client.o -o cliente

mainmenu.o: mainmenu.c mainmenu.h
	gcc -c mainmenu.c

quarto.o: quarto.c quarto.h
	gcc -c quarto.c

sala.o: sala.c sala.h
	gcc -c sala.c

temperatura.o: temperatura.c temperatura.h
	gcc -c temperatura.c

conect.o: conect.o conect.h
	gcc -c conect.c

client.o: client.c
	gcc -c client.c
